spring:
  application.name: workat_project

  datasource:
    url: "jdbc:mariadb://localhost:3306/miniProj-db2"
    username: "bituser"
    password: "1004"
    driver-class-name: org.mariadb.jdbc.Driver