spring:
  application.name: workat_project

  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${DATA_SOURCE_NAME}
    password: ${DATA_SOURCE_PWD}
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

naver:
  client-id: ${NAVER_CLIENT}
  client-secret: ${NAVER_SECRET_CLIENT}


payment:
  toss:
    test_client_key: ${TOSS_TEST_CLIENT}
    test_secrete_key: ${TOSS_TEST_SECRET}
    success_url: "http://localhost:8080/payment/toss/success"
    fail_url: "http://localhost:8080/payment/toss/fail"

cloud:
  aws:
    region:
      static: us-east-1
    s3:
      bucket: workatbucket
      folder:
        folderName1: place/
        folderName2: room/
        folderName3: review/
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}