spring:
  application.name: workat_project

  datasource:
    url: "jdbc:mariadb://localhost:3306/miniProj-db2"
    username: "bituser"
    password: "0000"
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
